version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongoc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

