# Use postgres/example user/password credentials

version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: note-admin
      POSTGRES_PASSWORD: dENgczA44IsDn
      POSTGRES_DB: note-db
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: note-admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: .Eq@KzmeHF4-u&n
